### ISSUE TITLE
Cannot Create a User

### ISSUE THREAD

**Issue by SteveWD** [StevenWeathers/exothermic-story-mapping#17]
Firstly this is a really good application - I'm trying to get into story mapping and this is a really good tool to be able to do that.  I am having a problem in that I cannot seem to create a user.  I believe this is probably my configuration/usage rather than a bug. 

I'm running the latest build using 'docker-compose up --build' on master.  The UI comes up and I can create storyboards as a Guest but I can't create a user.  

When I create an account nothing happens at all.  I have then tried to login using the credentials that I had previously used and I get an error.  There is no output in the docker CLI.  

I have tried this on both Win 10 and Ubuntu 20.04. 

Thanks,

Steve

**Comment by StevenWeathers** [comment]
@SteveWD Thanks for the notice, I have found the issue and fixed it in latest 0.14.0 release, please pull latest master.
